package choehaualen.breath.data.local

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Update
import choehaualen.breath.data.local.entity.UserEntity

/**
 * A Data Access Object for the [UserDatabase] used to execute CRUD operations.
 */
@Dao
interface UserDao {

    /**
     * Insert a new [UserEntity] into the database and return the autogenerated ID.
     * @param userEntity The entity to be inserted.
     */
    @Insert
    suspend fun insertUser(userEntity: UserEntity): Long

    /**
     * Returns an [UserEntity] from the database with the corresponding ID, otherwise returns null.
     * @param id The ID of the User.
     */
    @Query("SELECT * FROM user_table WHERE id = :id LIMIT 1")
    suspend fun getUserById(id: Long): UserEntity?

    /**
     * Update an existing [UserEntity] inside the database.
     * @param userEntity The entity to be updated.
     */
    @Update
    suspend fun updateUser(userEntity: UserEntity)

    /**
     * Delete an existing [UserEntity] from the database.
     *
     * ***WARNING: This action cannot be undone!***
     * @param userEntity The entity to be deleted.
     */
    @Delete
    suspend fun deleteUser(userEntity: UserEntity)

    /**
     * Flushes the whole database.
     *
     * ***WARNING: This will delete all the data!***
     */
    @Query("DELETE FROM user_table")
    suspend fun flushDatabase()

}